const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
  getPlatform: () => process.platform,
  getVersion: () => process.versions.electron,
  dbLogin: (username, password) => ipcRenderer.invoke('db-login', username, password),
  getPendudukList: () => ipcRenderer.invoke('db-get-penduduk-list'),
  getPendudukPindahList: () => ipcRenderer.invoke('db-get-penduduk-pindah-list'),
  getPendudukMeninggalList: () => ipcRenderer.invoke('db-get-penduduk-meninggal-list'),
  getPendudukById: (id) => ipcRenderer.invoke('db-get-penduduk-by-id', id),
  createPenduduk: (data) => ipcRenderer.invoke('db-create-penduduk', data),
  updatePenduduk: (id, data) => ipcRenderer.invoke('db-update-penduduk', id, data),
  deletePenduduk: (id) => ipcRenderer.invoke('db-delete-penduduk', id),
  getKeluargaList: () => ipcRenderer.invoke('db-get-keluarga-list'),
  getKeluargaByNoKK: (noKK) => ipcRenderer.invoke('db-get-keluarga-by-no-kk', noKK),
  getKeluargaMembers: (noKK) => ipcRenderer.invoke('db-get-keluarga-members', noKK),
  getTableList: () => ipcRenderer.invoke('db-get-table-list'),
  getTableData: (tableName) => ipcRenderer.invoke('db-get-table-data', tableName),
  runQuery: (query) => ipcRenderer.invoke('db-run-query', query),
  getStatistics: (options) => ipcRenderer.invoke('db-get-statistics', options),
  exportCSV: () => ipcRenderer.invoke('db-export-csv'),
  exportExcel: () => ipcRenderer.invoke('db-export-excel'),
  exportTemplateCSV: () => ipcRenderer.invoke('db-export-template-csv'),
  exportTemplateExcel: () => ipcRenderer.invoke('db-export-template-excel'),
  importCSV: () => ipcRenderer.invoke('db-import-csv'),
  importExcel: () => ipcRenderer.invoke('db-import-excel'),
  getReferences: (type) => ipcRenderer.invoke('db-get-references', type),
  getAllReferences: () => ipcRenderer.invoke('db-get-all-references'),
  createReference: (type, name) => ipcRenderer.invoke('db-create-reference', type, name),
  updateReference: (type, id, name) => ipcRenderer.invoke('db-update-reference', type, id, name),
  deleteReference: (type, id) => ipcRenderer.invoke('db-delete-reference', type, id),
  getProfile: (userId) => ipcRenderer.invoke('db-get-profile', userId),
  updateProfile: (data) => ipcRenderer.invoke('db-update-profile', data),
  updatePassword: (data) => ipcRenderer.invoke('db-update-password', data),
  resetData: (options) => ipcRenderer.invoke('db-reset-data', options),
  getAppInfo: () => ipcRenderer.invoke('app-get-info'),
  movePenduduk: (payload) => ipcRenderer.invoke('db-move-penduduk', payload)
});
